#pragma checksum "E:\CUC\Prueba Tecnica Rossmon\PruebaTecnica\PruebaTecnica\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "855A9236CCE832B3763C2322C3164760739236F1AB94CF16324983CA79C6A0CA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica
{
    partial class App : global::Windows.UI.Xaml.Application
    {
    }
}

